# Generated by Django 5.2.7 on 2025-10-31 07:49

from django.db import migrations


def create_sections(apps, schema_editor):
    ClassSection = apps.get_model("main", "ClassSection")
    letters = ["A", "B", "C", "D"]
    sections = []
    for year in range(1, 5):
        for letter in letters:
            section_id = f"{year}{letter}"
            sections.append(ClassSection(section_id=section_id, year=year))
    ClassSection.objects.bulk_create(sections, ignore_conflicts=True)


def delete_sections(apps, schema_editor):
    ClassSection = apps.get_model("main", "ClassSection")
    letters = ["A", "B", "C", "D"]
    ids = [f"{year}{letter}" for year in range(1, 5) for letter in letters]
    ClassSection.objects.filter(section_id__in=ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_classsection_question_survey_and_more"),
    ]

    operations = [
        migrations.RunPython(create_sections, delete_sections),
    ]
