# Generated by Django 5.2.7 on 2025-11-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_surveysubmission_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
