# Generated by Codex to align survey status naming with UI (open/closed/draft).
from django.db import migrations, models


def forward(apps, schema_editor):
    Survey = apps.get_model("main", "Survey")
    Survey.objects.filter(status__iexact="published").update(status="open")


def backward(apps, schema_editor):
    Survey = apps.get_model("main", "Survey")
    Survey.objects.filter(status__iexact="open").update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_survey_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(forward, backward),
    ]

